\input texinfo
@documentencoding UTF-8

@ifnottex
@paragraphindent 0
@end ifnottex

@node Top
@top Tetris BrickGame v1.0

@menu
* Вступление::
* Установка::
* Usage::
* Testing::
* Files::
* Makefile Targets::
@end menu

@node Вступление
@section Introduction

Это задание является первым из серии BrickGame. 

@node Установка
@section Installation

git clone XXX && make

@enumerate
@item
Выполнив @code{make install} в каталоге проекта.
@item
Игра будет установлена в каталог s21_BrickGame домашнего каталога. Если необходимо изменить каталог установки, то в @code{Makefile} переопределите переменную @code{DIR_GAME}.
@end enumerate

Что бы удалить игру выполните:

@enumerate
@item
@code{make uninstall}
@end enumerate

@node Usage
@section Usage

To run the game:

@enumerate
@item
После установки перейдите в каталог установки и запустите исполняемый файл @file{tetris}.
@end enumerate

Управление:

@itemize
@item
@strong{<-}: переместить блок влево.
@item
@strong{->}: переместить блок вправо.
@item
@strong{стрелка вниз}: сразу же опустить блок.
@item
@strong{пробле}: повернуть блок.
@item
@strong{P}: поставить на паузу игру.
@item
@strong{Esc}: законить и выйти из игры.
@end itemize

@node Тестирование
@section Testing

Скомпилировать и запустить тесты:

@enumerate
@item
Выполнив @code{make test} запустятся тесты.
@end enumerate

Просмотреть покрытие тестами выполните @code{make gcov_report}.

@node Файлы
@section Files

Структура проекта:

@itemize
@item
@file{brick_game/tetris/}: Файлы отвечающие за логику передвижения и закреления блоков наигровом поле, сохранения результатов.
@item
@file{gui/cli/}: Интерфейс программы.
@item
@file{inc/}: Хэдерфайлы бэкенда и фронтенда.
@item
@file{tests/}: файлы тестирования.
@item
@file{Makefile}: конфигурационный файл сборки программы.
@item
@file{readme.texi}: Описание проекта.
@end itemize

@node Цели Makefile
@section Makefile Targets

@itemize
@item
@code{all}: Очистка, компиляция и установка программы в каталог.
@item
@code{install}: Создание необходимых папок, сборка и установка программы в заданый каталог.
@item
@code{uninstall}: Удаление всех файлов установки и файлов которые возникли в результате работы Тетриса.
@item
@code{tetris}: Компиляция файлов прокета.
@item
@code{mkdir}: создание необходимых каталогов.
@item
@code{test}: Runs the test suite.
@item
@code{clean}: Очистка файлов которые согли были быть созаданы в результате работы целей мэйкфайла.
@item
@code{gcov_report}: Создание отчета покрытия тестами.
@item
@code{valgrind}: Запуск тестов и поиск утечек памяти.
@item
@code{dvi}: создание файла документации по проекту.
@end itemize

@bye


 /\_/\     (\(\
( o.o )    (○∙○)
 > ^ <     > ^ <  



